ShortLinkDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import home, redirect_page
from main.views import other_page
from main.views import SLLoginView
from main.views import profile
from main.views import SLLogoutView
from main.views import ChangeUserInfoView
from main.views import SLPasswordChangeView
from main.views import SLPasswordResetView, SLPasswordResetDoneView
from main.views import SLPasswordResetConfirmView, SLPasswordResetCompleteView
from main.views import RegisterUserView, RegisterDoneView
from main.views import user_activate
from main.views import DeleteUserView


app_name = 'main'
urlpatterns = [
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/login/', SLLoginView.as_view(), name='login'),
    path('accounts/logout/', SLLogoutView.as_view(), name='logout'),

    path('accounts/password/change/', SLPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_reset/', SLPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', SLPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password_reset/<uidb64>/<token>', SLPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/password_reset/done/', SLPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('<str:page>/', other_page, name='other'),
    path('<str:token>/', redirect_page, name='link'),
    path('', home, name='index'),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Link(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             null=True,
                             blank=True
                             )
    long_link = models.URLField(unique=True)
    short_link = models.URLField(unique=True)
    token = models.CharField(max_length=6, unique=True)

    def __str__(self):
        return self.long_link

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from main.apps import user_registered


class LinkForm(forms.Form):
    long_link = forms.URLField(required=True)


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class RegisterUserForm(forms.ModelForm):

    email = forms.EmailField(required=True, label='Email')
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password (again)',
                                widget=forms.PasswordInput,
                                help_text='Enter the same password for check')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError("passwords don't matched", code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.exceptions import TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import UpdateView, TemplateView, CreateView, DeleteView
from django.db import IntegrityError

from main.forms import ChangeUserInfoForm, RegisterUserForm
from main.link_shorter import UrlShorten
from main.utilities import signer
from main.forms import LinkForm
from main.models import Link


def home(request):
    if request.method == 'POST':
        link_form = LinkForm(request.POST)
        context = {'form': link_form}
        if link_form.is_valid():
            token = UrlShorten.create_unique(str(link_form['long_link']))
            short_link = request.get_host() + '/' + token
            long_link = link_form.cleaned_data['long_link']
            if request.user.is_authenticated:
                try:
                    Link.objects.get_or_create(
                        user=request.user,
                        long_link=long_link,
                        short_link=short_link,
                        token=token
                    )
                except IntegrityError:
                    pass
            context['long_link'] = long_link
            context['short_link'] = short_link
            return render(request, 'main/index.html', context)
        return render(request, 'main/index.html', context)
    else:
        form = LinkForm()
        context = {'form': form}
        return render(request, 'main/index.html', context)


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def redirect_page(request, token):
    redirect_link = get_object_or_404(Link, token=token).long_link
    return redirect(redirect_link)


class SLLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    links = Link.objects.filter(user=request.user.id).all()
    if links:
        context = {'links': links}
        return render(request, 'main/profile.html', context)
    return render(request, 'main/profile.html')


class SLLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя успешно изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class SLPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class SLPasswordResetView(PasswordResetView, SuccessMessageMixin, LoginRequiredMixin):
    template_name = 'main/password_reset_form.html'
    subject_template_name = 'templates/email/reset_subject.txt'
    email_template_name = 'templates/email/reset_email.txt'
    success_url = reverse_lazy('main:password_reset_done')
    success_message = 'Пароль пользователя сброшен'


class SLPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'main/password_reset_done.html'


class SLPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'main/confirm_password.html'


class SLPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'main/password_confirmed.html'


class PasswordDoneView(TemplateView):
    template_name = 'main/password_reset_form.html'


class RegisterUserView(CreateView):
    model = User
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(User, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

main/templates/main/activation_done.html
{% extends 'layout/basic.html' %}

{% block title %}
    User already has been activated
{% endblock %}

{% block content %}
    <h2>Activation </h2>
    <p>User already has been activated.</p>
    <p><a href="{% url 'main:login' %}">Login</a></p>
{% endblock %}

main/templates/main/bad_signature.html
{% extends 'layout/basic.html' %}

{% block title %}
    Activation failed
{% endblock %}

{% block content %}
    <h2>Activation </h2>
    <p>Activation failed</p>
    <p><a href="{% url 'main:register' %}">Try again</a></p>
{% endblock %}

main/templates/main/change_user_info.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}
    Update personal data
{% endblock %}

{% block content %}
    <h2>Update personal data of {{ user.name }}</h2>
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Save' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/delete_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}
    Delete user
{% endblock %}

{% block content %}
    <h2>Delete user {{ object.username }}</h2>
    <form method="post">
    {% csrf_token %}
    {% buttons submit='Delete' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %}{{ index }}{% endblock %}

{% block content %}
    <body class="text-center mx-auto">
        <h2 class="h3 mb-3 font-weight-normal" style="margin-top:50px">Generate short link</h2>
        <div class="container-xl" style="margin-top:50px">
            <form method="post" class="form-signin" style="color:white">
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                {% bootstrap_button content="Generate" button_class="btn btn-success" extra_classes="margin-top:20px" %}
            </form>
                <div style="margin-top: 20px" class="card text-center bg-dark">
                  <div class="card-body">
                      {% if short_link %}
                          <a class="card-title" href="{{ long_link }}">{{ short_link }}</a>
                      {% else %}
                          <h5 class="card-title">Short link</h5>
                  </div>
                </div>
            {% endif %}
        </div>
    </body>
{% endblock %}

main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Login{% endblock %}

{% block content %}
    <body class="text-center">
        <div class="container">
            <h2 class="h3 mb-3 font-weight-normal">Login</h2>
            {% if user.is_authenticated %}
                <p class="h5 mb-3 font-weight-normal">You just have been logged</p>
            {% else %}
                <form method="post" class="form-signin" style="color:white">
                    {% csrf_token %}
                    {% bootstrap_form form layout='horizontal' %}
                    <input type="hidden" name="next" value="{{ next }}">
                    {% buttons submit="Login" %}{% endbuttons %}
                 </form>
            {% endif %}
        </div>
    </body>
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
    <h2>Logout</h2>
    <p>Lougout has been successfully</p>
{% endblock %}

main/templates/main/password_change.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}
    Reset password
{% endblock %}

{% block content %}
    <h2>Reset password {{ user.username }}</h2>
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Reset' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/password_reset_done.html
{% extends 'layout/basic.html' %}

{% block title %}
    Reset password
{% endblock %}

{% block content %}
    <h2>Reset password</h2>
    <p>On your email address, sent message for reset password.</p>
{% endblock %}

main/templates/main/password_reset_form.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}
    Reset password
{% endblock %}

{% block content %}
    <h2>Reset password {{ user.username }}</h2>
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сбросить' %}{% endbuttons %}
    </form>
{% endblock %}

main/templates/main/profile.html
{% extends 'layout/basic.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
    <div class="text-center">
        <div class="row" style="margin-top:20px; margin-left:20px">
           <div class="col-8">
              <h2>{{ user.username }}'s profile</h2>
              <br>
           {% if links %}
              <table class="table table-hover table-dark">
                 <thead>
                    <tr>
                       <!-- Your Columns HERE -->
                       <th scope="col">Original link</th>
                       <th scope="col">Short link</th>
                    </tr>
                 </thead>
                 <tbody>
                    <!-- Your rows inside the table HERE: -->
                    {% for link in links %}
                    <tr>
                        <td><a href="{{ link.long_link }}">{{ link.long_link }}</a></td>
                        <td><a href="{{ link.long_link }}">{{ link.short_link }}</a></td>
                    </tr>
                    {% endfor %}
                 </tbody>
              </table>
           {% endif %}
           </div>
        </div>
    </div>
{% endblock %}

main/templates/main/register_done.html
{% extends 'layout/basic.html' %}

{% block title %}
    Registration almost complete!
{% endblock %}

{% block content %}
    <h2>Registration</h2>
    <p>Registration almost complete!</p>
{% endblock %}

main/templates/main/register_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}
    Registration
{% endblock %}

{% block content %}
    <body class="text-center">
        <div class="container">
            <h2 class="h3 mb-3 font-weight-normal" style="margin-top:20px">Registration new user</h2>
            <br>
                <form method="post" class="form-register" style="color:white">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons submit='Submit' %}{% endbuttons %}
                </form>
        </div>
    </body>
{% endblock %}

main/templates/main/user_is_activated.html
{% extends 'layout/basic.html' %}

{% block title %}
    Activation
{% endblock %}

{% block content %}
    <h2>Activation </h2>
    <p>Activation done!.</p>
    <p><a href="{% url 'main:login' %}">Login</a></p>
{% endblock %}